### PR TITLE
add the controlpanel adapter required to show the controlpanel in Volto

### PR DESCRIPTION
**Pull request by erral**
This this adapter in place, the control panel to configure the captcha will be shown in Volto too.

### CODE REVIEW

**Comment by erral** [comment]
cc: @mamico @giuliaghisini

**Comment by 1letter** [comment]
I can't say anything to controlpanels which are needed in Volto. The Code looks ok. But a Test failed.

```
Failure in test /devel/projects/collective.z3cform.norobots/src/collective/z3cform/norobots/tests/doctests.rst
Failed doctest test for doctests.rst
  File "/devel/projects/collective.z3cform.norobots/src/collective/z3cform/norobots/tests/doctests.rst", line 0

----------------------------------------------------------------------
File "/devel/projects/collective.z3cform.norobots/src/collective/z3cform/norobots/tests/doctests.rst", line 74, in doctests.rst
Failed example:
    foo_form.widgets.keys()
Expected:
    ['id', 'norobots']
Got:
    odict_keys(['id', 'norobots'])
```
Look like a failing test, independend of your changes. The fix of this test is trivial. Perhaps you can include this in your PR?

**Review by 1letter — COMMENTED** [review]
LGTM

**Comment by erral** [comment]
@1letter I fixed the test and pushed again. I run the tests locally and they pass, but I see there's no github actions integration. I can try to prepare such an integration as part of another PR.

**Review by 1letter — APPROVED** [review]

**Comment by 1letter** [comment]
@erral If you have the time, sure. PR is evertime welcome! thanks for contributing.

**Comment by 1letter** [comment]
@MrTango can you review, like requested? and can you make a new release please?

**Comment by erral** [comment]
@MrTango can you check this and make a release if possible?

**Pull request merged**
