### PR TITLE
GA setup

### PR DESCRIPTION
**Pull request by erral**

### CODE REVIEW

**Comment by erral** [comment]
Ains, setting up black, code-analysis and stuff is hard... although code-analysis should follow setup.cfg configuration, it complains about W503 and C812... :sleepy:

**Comment by 1letter** [comment]
@erral i have play a little bit with this branch, only one build fails. i'm not sure, if the use of code-analysis the right way. perhaps are seperate github actions for black, isort and flake8 the cleaner way?

**Comment by erral** [comment]
That could be the solution indeed, let me have a look at it.

**Comment by erral** [comment]
@1letter I have removed the code-analysis step and extracted black and flake8 calls to separate jobs like it's done in [plone.restapi](https://github.com/plone/plone.restapi/tree/master/.github/workflows)

**Comment by erral** [comment]
@MrTango can you check this and make a release if possible?

**Review by MrTango — APPROVED** [review]
LGTM

**Comment by MrTango** [comment]
@erral done

**Pull request merged**
