### PR TITLE
Refactor Package with plone/meta - introduce only Plone 6 support

### LINKED ISSUE #24: Plone 6 plone.app.discussion form the question is not change on reload
The question is stay the same, so it actually does not really offer protection.

### PR DESCRIPTION
**Pull request by 1letter**
- refactor package with plone/meta
- update imports, linting and code format
- remove buidlout related files
- remove deprecated imports plone.app.z3cform
- add mx.ini
- add a browserlayer
- make the widget BS5 ready, use floating labels https://getbootstrap.com/docs/5.2/forms/floating-labels/

i think a new release is needed. Only for Plone 6 and higher.

some things should be do:

- news support
- ~update readme~
- ~update the norobot macro~
- ~more tests~

### CODE REVIEW

**Comment by erral** [comment]
I see this OK but I am not used to the new non-buildout-way of organizing the package. So I will request our meta-master a review.

In any case this requires increasing the version number to the next major version.

**Review by erral — COMMENTED** [review]
I see this OK but I am not used to the new non-buildout-way of organizing the package. So I will request our meta-master a review.

In any case this requires increasing the version number to the next major version.

**Comment by MrTango** [comment]
I'm not so sure that i would remove buildout at this point, for development setups.
It is robust and well known.
There is not much advantages in change this here.
But if you change it, make sure that it is very clear how to do all the things we use to be able to do with a traditional setup.
So far i have seen a bit of a wild west in new buildout free setups.
We need well documented and tested standards here.
When we reach this point, we could also rework the plonecli templates to use the new approach.
But i would like to see it really working well for a while, before going there.

**Comment by 1letter** [comment]
@MrTango is there a roadmap for the switch? I see the plone/meta config in many packages of the plone.xxx namespace. Plone's containers are pip-based. I didn't know what the right way was. I use pip based setups with mxdev in all my packages and have no problems. but this is a discussion with religious potential ;-)

**Comment by MrTango** [comment]
Ok, i had a look at the current meta setup, looks good and is recommended also for addons.
If everything works and the README points the developers in the right direction, all good.
I'll have a closer look and play with it as soon as i can.
Eventually, this will become also standard for addons made by plonecli.
But I'm not in a hurry with it.
Let's battle proof it before we do that.

**Review by MrTango — COMMENTED** [review]
Where do we define the test Matrix here?
We state that this will run in Plone 6.0/6.1 and Python 3.9-3.11, how are we making sure that it will e tested for all variants?
@gforcada hints?

**Review by MrTango — APPROVED** [review]

**Pull request merged**
